flask:
    DEBUG: True
    TESTING: True
    CSRF_ENABLED: False
    SECRET: supersecret
    CELERY_BROKER_URL: redis://
    CELERY_RESULT_BACKEND: redis://

frontend_app:
    name: frontend_app
    broker_url: redis://
    result_backend: redis://
    task_default_queue: frontend_app

engine_app:
    name: engine_app
    broker_url: redis://
    result_backend: redis://
    task_default_queue: engine_app

scan_app:
    name: scan_app
    broker_url: redis://
    result_backend: redis://
    task_default_queue: scan_app